I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script
    init python:
  File "game/script.rpy", line 194, in <module>
    self.speed = random.uniform(0.025, 0.035)  # Original was 0.015 to 0.025
NameError: name 'self' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script
    init python:
  File "D:\Coding\Installed\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Coding\Installed\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 194, in <module>
    self.speed = random.uniform(0.025, 0.035)  # Original was 0.015 to 0.025
NameError: name 'self' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
BoatGame 1.0
Mon Apr 28 00:49:05 2025
